---
- name: Test Playbook
  hosts: all
  gather_facts: no
  remote_user: ansibler
  become: yes

  pre_tasks:
    - name: Set LED trigger
      command: sudo sh -c "echo timer > /sys/class/leds/led1/trigger"

  tasks:
    - name: Generate user
      user:
        name: runner
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_comment: runner@raspberrypi.local

    - name: Genenerate deploy key for backend
      openssh_keypair:
        owner: runner
        group: ansibler
        mode: 664
        path: "/home/runner/.ssh/id_rsa_backend"
        type: rsa
        size: 4096
        comment: "runner@backend"
      register: key_backend

    - name: Genenerate deploy key for frontend
      openssh_keypair:
        owner: runner
        group: ansibler
        mode: 664
        path: /home/runner/.ssh/id_rsa_frontend
        type: rsa
        size: 4096
        comment: "runner@frontend"
      register: key_frontend

    - name: Print deploy key for backend
      debug:
        var: key_backend.public_key

    - name: Print deploy key for frontend
      debug:
        var: key_frontend.public_key

  post_tasks:
    - name: Restore LED trigger
      command: sudo sh -c "echo heartbeat > /sys/class/leds/led1/trigger"
