---
- name: Test Playbook
  hosts: all
  gather_facts: no
  remote_user: ansibler
  become: yes

  pre_tasks:
    - name: Set LED trigger
      command: sudo sh -c "echo timer > /sys/class/leds/led1/trigger"

  roles:
    - power
    - account
    # - packages
    - firewall

  post_tasks:
    - name: Restore LED trigger
      command: sudo sh -c "echo mmc0 > /sys/class/leds/led1/trigger"
