---
- name: Test Playbook
  hosts: all
  gather_facts: no
  remote_user: ansibler
  become: yes

  pre_tasks:
    - name: Set LED trigger
      command: sudo sh -c "echo timer > /sys/class/leds/led1/trigger"

  tasks:
    - name: Generate user
      user:
        name: runner
        generate_ssh_key: yes
        ssh_key_bits: 4096
        ssh_key_comment: runner@raspberrypi.local

    - name: Genenerate deploy key for backend
      openssh_keypair:
        owner: runner
        group: ansibler
        mode: 664
        path: "/home/runner/.ssh/id_rsa_backend"
        type: rsa
        size: 4096
        comment: "runner@backend"
      register: key_backend

    - name: Genenerate deploy key for frontend
      openssh_keypair:
        owner: runner
        group: ansibler
        mode: 664
        path: /home/runner/.ssh/id_rsa_frontend
        type: rsa
        size: 4096
        comment: "runner@frontend"
      register: key_frontend

    - name: Print deploy key for backend
      debug:
        var: key_backend.public_key

    - name: Print deploy key for frontend
      debug:
        var: key_frontend.public_key

    - name: Stop services
      ansible.builtin.shell: docker compose --file /home/runner/docker-compose.yml stop

    - name: Copy docker compose file
      ansible.builtin.copy:
        src: ./docker-compose.yml
        dest: /home/runner/docker-compose.yml
        owner: runner
        group: runner
        mode: "0644"
    
    - name: Clone backend repo
      ansible.builtin.git:
        repo: git@github.com:pmerlo/meals-backend.git
        dest: /home/runner/meals-backend
        key_file: /home/runner/.ssh/id_rsa_backend
        accept_hostkey: yes
        force: yes

    - name: Clone frontend repo
      ansible.builtin.git:
        repo: git@github.com:pmerlo/meals-dist.git
        dest: /home/runner/meals-dist
        key_file: /home/runner/.ssh/id_rsa_frontend
        accept_hostkey: yes
        force: yes
    
    - name: Build containers
      ansible.builtin.shell: docker compose --file /home/runner/docker-compose.yml build

    - name: Launch services
      ansible.builtin.shell: docker compose --file /home/runner/docker-compose.yml up --detach
      

  post_tasks:
    - name: Restore LED trigger
      command: sudo sh -c "echo heartbeat > /sys/class/leds/led1/trigger"
