---
- name: Update apt cache
  apt:
    update_cache: yes

- name: Update all packages
  apt:
    upgrade: yes

- name: Add basic tools
  apt:
    name:
      - git
      - curl
      - htop
      - httpie
