---
- name: Ensure ufw is installed
  apt:
    name: ufw

- name: Limit SSH protocol
  community.general.ufw:
    rule: limit
    to_port: ssh

- name: Allow  access to tcp port 80
  community.general.ufw:
    rule: allow
    port: "80"
    proto: tcp

- name: Deny incoming connections
  community.general.ufw:
    direction: incoming
    default: deny

- name: Allow outgoing connections
  community.general.ufw:
    direction: outgoing
    default: allow

- name: Enable firewall
  community.general.ufw:
    state: enabled
