---
- name: Check if installation script exists
  stat:
    path: "{{ DOCKER_INSTALL_SCRIPT }}"
  register: script

- name: Download docker setup script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: "{{DOCKER_INSTALL_SCRIPT}}"
    mode: "0700"
  when: not script.stat.exists

- name: Check if installation already ran
  stat:
    path: "{{ DOCKER_INSTALL_LOG }}"
  register: log

- name: Execute docker setup sript
  ansible.builtin.shell: "{{DOCKER_INSTALL_SCRIPT}} >> {{DOCKER_INSTALL_LOG}}"
  when: not log.stat.exists
