---
- name: Check if installation script exists
  stat:
    path: "{{ DOCKER_INSTALL_SCRIPT }}"
  register: script

- name: Download docker setup script
  ansible.builtin.get_url:
    url: https://get.docker.com
    dest: "{{DOCKER_INSTALL_SCRIPT}}"
    mode: "0700"
  when: not script.stat.exists

- name: Check if installation already ran
  stat:
    path: "{{ DOCKER_INSTALL_LOG }}"
  register: log

- name: Execute docker setup sript
  ansible.builtin.shell: "{{DOCKER_INSTALL_SCRIPT}} >> {{DOCKER_INSTALL_LOG}}"
  when: not log.stat.exists

- name: "Generate user with ssh key pair"
  user:
    name: runner
    generate_ssh_key: yes
    ssh_key_bits: 4096
    ssh_key_comment: runner@raspberrypi.local
  register: user_result

- name: "Store public key"
  set_fact:
    public_key: "{{user_result.ssh_public_key}}"

- name: "Print public key"
  debug:
    var: public_key
